[phases.build]
cmds = [
  "cd backend && npm install",
  "cd backend && npm run build",
  "cd backend && npx prisma generate"
]

[phases.setup]
nixPkgs = ['nodejs_20', 'npm-9_x']

[start]
cmds = [
  "cd backend && npx prisma migrate deploy",
  "cd backend && npm run db:seed",
  "cd backend && npm start"
]
